changelog:
  categories:
    - title: Enhancement
      labeles:
        - enhancement
    - title: Bug Fixes
      labeles:
        - bug
        - fixes
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot

